### ISSUE TITLE
Rework gui tests (concerning feature dialog)

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#182]
In the `SwingMenuGuiTest` a rule is used to state the non-closing feature definition dialog as test success. This seems to be a workaround with consequences we might not foresee right now.
Find a better way of coping the actual problem: Check the verification result, computed when the `OK` button of the `FeatureDefinitionDialog` was clicked.

---

Noticable links: http://java.dzone.com/articles/allowing-junit-tests-pass-test
http://stackoverflow.com/questions/4055022/mark-unit-test-as-an-expected-failure-in-junit

**Comment by FRosner** [comment]
https://github.com/junit-team/junit/issues/771#issuecomment-29219828 should be a nice solution to wait for the timeout. We could then expect the TimeoutException. Would that work?

**Comment by Husterknupp** [comment]
I think that will help us very much, indeed. It is very nice that they fixed this issue and that they did not need much time for that. @FRosner thank you for triggering this issue off.

**Comment by FRosner** [comment]
We should rename the `TIMEOUT` and `TIMEOUT_LONG` constants to something like `ADD_FEATURE_TIMEOUT` and `EDIT_FEATURE_TIMEOUT`.

**Comment by FRosner** [comment]
Pull request: https://github.com/junit-team/junit/pull/777

**Comment by Husterknupp** [comment]
@FRosner ​I am a little bit confused on how to deal with Assertions in a thread. The way I wanted to improve a few methods would be to start a Thread, let it click a button and then let it check an internal state via assertion.

The thing I don't know is how to return the Assertion result back to the method which starts the tread. Can you give me some advise, please?

**Comment by FRosner** [comment]
If writing `assertThat` directly inside the thread is not working, you could try to return some kind of boolean or result object.

See [Callables](http://openbook.galileocomputing.de/javainsel9/javainsel_14_004.htm#mj1b2390839194e0171bbe333adf513efb) and Future. Maybe having a look at this chapter as a whole helps as well.

**Comment by FRosner** [comment]
Reworking is needed because the assertions inside of a thread will not cause the test to fail but rather throw an exception inside that thread:

```
Exception in thread "Thread-40" org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.fest.assertions.ConstructorInvoker.newInstance(ConstructorInvoker.java:36)
    at org.fest.assertions.ComparisonFailureFactory.newComparisonFailure(ComparisonFailureFactory.java:60)
    at org.fest.assertions.ComparisonFailureFactory.comparisonFailure(ComparisonFailureFactory.java:46)
    at org.fest.assertions.Fail.comparisonFailed(Fail.java:83)
    at org.fest.assertions.Fail.failIfNotEqual(Fail.java:71)
    at org.fest.assertions.GenericAssert.isEqualTo(GenericAssert.java:217)
    at org.fest.assertions.BooleanAssert.isEqualTo(BooleanAssert.java:73)
    at org.fest.assertions.BooleanAssert.isTrue(BooleanAssert.java:55)
    at de.frosner.datagenerator.gui.main.SwingMenuGuiTest$3.run(SwingMenuGuiTest.java:719)
    at java.lang.Thread.run(Thread.java:619)
```
